
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nearsure_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nearsure_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: nearsure_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 30s
      timeout: 30s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: nearsure_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - NODE_OPTIONS=--max-old-space-size=2048
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  api:
    container_name: nearsure_api
    build:
      context: .
      dockerfile: src/NearsureApp.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=nearsure_db;Username=user;Password=password
    depends_on:
      - db
      - elasticsearch

  client:
    container_name: nearsure_client
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: nearsure_keycloak
    ports:
      - "8181:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - "start-dev"

volumes:
  postgres_data:
  elastic_data:
